// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtTnWHKfNzXjaLgorMj_EnBtGtK45PXhE',
    appId: '1:800784125007:web:aa20d3df3c586b7c4c2e3a',
    messagingSenderId: '800784125007',
    projectId: 'qr-code-aa74c',
    authDomain: 'qr-code-aa74c.firebaseapp.com',
    storageBucket: 'qr-code-aa74c.appspot.com',
    measurementId: 'G-6C8N14JPXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRyH9VPENuNmbOLiOyw8KuUhAl55XCsOU',
    appId: '1:800784125007:android:c115f9f0df6348f04c2e3a',
    messagingSenderId: '800784125007',
    projectId: 'qr-code-aa74c',
    storageBucket: 'qr-code-aa74c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASRibODh4RkdfROMEauEQ6WAHmA2RB1xY',
    appId: '1:800784125007:ios:5ed7b08fd517e8674c2e3a',
    messagingSenderId: '800784125007',
    projectId: 'qr-code-aa74c',
    storageBucket: 'qr-code-aa74c.appspot.com',
    iosClientId: '800784125007-k2er6r4vlmbfc6do322aonkhqks4ppbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASRibODh4RkdfROMEauEQ6WAHmA2RB1xY',
    appId: '1:800784125007:ios:5c9efa6dc948d1fb4c2e3a',
    messagingSenderId: '800784125007',
    projectId: 'qr-code-aa74c',
    storageBucket: 'qr-code-aa74c.appspot.com',
    iosClientId: '800784125007-c5m3eisdogd58lim5uf9bu1cdci7onfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance.RunnerTests',
  );
}
